### ISSUE TITLE
Mocking support

### ISSUE THREAD

**Issue by chrylis** [kjbekkelund/karma-requirejs#10]
I am wanting to mock out a 3rd-party API to test some of my wiring code, but I'm having trouble figuring out how to do that with Karma and RequireJS. Is that something that's straightforward to do with this module? If so, could you put an example in the docs, and if not, what would it take to make it feasible?

**Comment by nextlevelshit** [comment]
What do you mean by 3rd party? Something like a script from CDN or a node module? Maybe you'd like to refer to a gist, project on github or simply a code example.

**Comment by chrylis** [comment]
I actually found a solution to this and forgot I had the issue outstanding. Both SquireJS and Jest handle the mocking aspect cleanly and cooperate nicely with Karma.
